/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://mganfwls2jhlhf44bs2o34frha.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-6od65mmtjbcz5c3ucddob35rmy",
    "aws_cognito_identity_pool_id": "us-east-1:f313052e-fb6f-4a1b-9437-3af6eeb04274",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_uOyyNkSlL",
    "aws_user_pools_web_client_id": "57lmva43qlo6o4ba4lo1pq3chg",
    "oauth": {}
};


export default awsmobile;
